version: "3.7"

networks:
  datams-network:
    external: false
    
services:
  datams:
    image: datams/python:3.10.13-slim
    container_name: datams
    restart: always
    build:
      dockerfile: "./docker/datams.dockerfile"
    networks:
      - datams-network
    ports:
      - "${DATAMS_EXPOSED_PORT}:8000"
    environment:
      - DATAMS_CONFIG=${DATAMS_CONFIG}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
      - NUM_GUNICORN_WORKERS=${NUM_GUNICORN_WORKERS}
    command:
      - "/app/gunicorn_entrypoint.sh"     
    logging:
      options:
        max-size: "100m"
        max-file: "10"
        compress: "true"
    volumes:
      - "${HOST_DISCOVERY_DIR}:/app/run/discovery"
      - "${HOST_UPLOADS_DIR}:/app/run/uploads"
      - "${HOST_INFO_DIR}:/app/run/info"
    depends_on:
      - redis
      - postgres
    
  celery:
    image: datams/python:3.10.13-slim
    container_name: celery
    restart: always
    build:
      dockerfile: "./docker/datams.dockerfile"
    networks:
      - datams-network
    environment:
      - DATAMS_CONFIG=${DATAMS_CONFIG}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
      - NUM_GUNICORN_WORKERS=${NUM_GUNICORN_WORKERS}
    command:
      - "/app/celery_entrypoint.sh"
    logging:
      options:
        max-size: "100m"
        max-file: "10"
        compress: "true"
    volumes:
      - "${HOST_DISCOVERY_DIR}:/app/run/discovery"
      - "${HOST_UPLOADS_DIR}:/app/run/uploads"
        
    depends_on:
      - redis
      - postgres
    
   
  redis:
    image: redis
    container_name: redis
    restart: always
    networks:
      - datams-network
    # ports:
    #   - 6379:6379
    logging:
      options:
        max-size: "100m"
        max-file: "10"
        compress: "true"
      
  postgres:
    image: datams/postgres:15-alpine3.18
    container_name: postgres
    build:
      dockerfile: "./docker/postgres.dockerfile"
    restart: always
    networks:
      - datams-network
    # ports:
    #   - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    logging:
      options:
        max-size: "100m"
        max-file: "10"
        compress: "true"
    volumes:
      - "postgres-volume:/var/lib/postgresql/data"
      - "./docker/datams.sql:/docker-entrypoint-initdb.d/init.sql"
      
volumes:
  postgres-volume:
    name: ${HOST_POSTGRES_VOLUME}